# Generated by Django 4.1.5 on 2023-01-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('seat_list', models.IntegerField(default=10)),
                ('source', models.CharField(max_length=30)),
                ('dest', models.CharField(max_length=30)),
                ('entiryhour', models.DecimalField(decimal_places=0, max_digits=2)),
                ('entirymin', models.DecimalField(decimal_places=0, max_digits=2)),
                ('exithour', models.DecimalField(decimal_places=0, max_digits=2)),
                ('exitmin', models.DecimalField(decimal_places=0, max_digits=2)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserve.driver')),
            ],
        ),
    ]
