# Generated by Django 4.1.5 on 2023-01-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seat_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='seat_num_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
