# Generated by Django 4.1.5 on 2023-01-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0002_bus_seat_num_bus_seat_num_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='number',
            new_name='bus_number',
        ),
    ]
