# Generated by Django 4.1.5 on 2023-01-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='seat_number',
        ),
        migrations.AlterField(
            model_name='bus',
            name='entiry',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
