# Generated by Django 4.1.5 on 2023-01-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_remove_bus_seat_number_alter_bus_entiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='exit',
            field=models.TimeField(auto_now=True),
        ),
    ]
